apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  ports:
    - port: 25565
      protocol: TCP
      name: tcp
    - port: 25565
      protocol: UDP
      name: udp
  clusterIP: None
  selector:
    app: minecraft
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft
  serviceName: minecraft
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      initContainers:
        - name: download-world-save
          image: amazon/aws-cli
          command:
            - s3
            - cp
            - s3://jsj-mineraft-backups
            - latest.tar.gz
            - /usr/app/mineraft/latest.tar.gz
          volumeMounts:
            - name: base
              mountPath: /usr/app/mineraft
          env:
            - name: AWS_REGION
              value: eu-west-1
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: accessKeyId
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secretAccessKey
        - name: extract-world-save
          image: busybox
          command:
            - sh
            - -c
            - 'cd /usr/app/minecraft && tar xf /usr/app/mineraft/latest.tar.gz'
          volumeMounts:
            - name: base
              mountPath: /usr/app/mineraft
      containers:
        - name: minecraft
          image: openjdk:11
          command:
            - -jar
            - /usr/app/minecraft/spigot-1.16.1.jar
          ports:
            - containerPort: 25565
              protocol: TCP
              name: tcp
            - containerPort: 25565
              protocol: UDP
              name: udp
          volumeMounts:
            - name: base
              mountPath: /usr/app/mineraft
  volumeClaimTemplates:
    - metadata:
        name: base
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 20Gi
