apiVersion: v1
kind: Service
metadata:
  name: minecraft-tcp
  labels:
    app: minecraft
  annotations:
    metallb.universe.tf/allow-shared-ip: minecraft
spec:
  ports:
    - port: 25565
      protocol: TCP
      name: tcp
  type: LoadBalancer
  loadBalancerIP: 10.5.0.99
  selector:
    app: minecraft
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-udp
  labels:
    app: minecraft
  annotations:
    metallb.universe.tf/allow-shared-ip: minecraft
spec:
  ports:
    - port: 25565
      protocol: UDP
      name: udp
  type: LoadBalancer
  loadBalancerIP: 10.5.0.99
  selector:
    app: minecraft
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft
  serviceName: minecraft
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      initContainers:
        - name: download-world-save
          image: amazon/aws-cli
          command:
            - sh
            - -c
            - "test '[[ ! -f /usr/app/minecraft/server.jar ]] && aws s3 cp s3://jsj-minecraft-backups/latest.tar.gz latest.tar.gz'"
          workingDir: /usr/app/minecraft
          volumeMounts:
            - name: base
              mountPath: /usr/app/minecraft
          env:
            - name: AWS_REGION
              value: eu-west-1
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: accessKeyId
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secretAccessKey
        - name: extract-world-save
          image: busybox
          command:
            - sh
            - -c
            - "test '[[ ! -f /usr/app/minecraft/server.jar ]] && tar xf /usr/app/minecraft/latest.tar.gz'"
          workingDir: /usr/app/minecraft
          volumeMounts:
            - name: base
              mountPath: /usr/app/minecraft
      containers:
        - name: minecraft
          image: openjdk:11
          command:
            - java
            - -jar
            - /usr/app/minecraft/server.jar
          workingDir: /usr/app/minecraft
          ports:
            - containerPort: 25565
              protocol: TCP
              name: tcp
            - containerPort: 25565
              protocol: UDP
              name: udp
          volumeMounts:
            - name: base
              mountPath: /usr/app/minecraft
  volumeClaimTemplates:
    - metadata:
        name: base
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 20Gi
